#!/usr/bin/env python3
"""SECUR1/SECUR2.PRG decoder + the ebas32.dll master-password chain —
rev 8 closure of the "encrypted SECUR pseudocode" blocker.

Chain reversed from ebas32.dll (all addresses are VA, image base
0x10000000, file md5 == shipping distribution):

  FUN_100024d0  embedded obfuscated blob @0x1002e12e (.rdata):
                  [+0x00..0x10] expected 16-byte master-file header
                  [+0x1c..0x20] master FILENAME as hex nibbles
                  [+0x16..0x26] XOR/divisor key bytes
                  [+0x2a..0x34] final XOR mask
  FUN_10002330  filename = hex(blob[0x1c:0x20]) → "63477BC6"
  FUN_10002430  path = directory of ebas32.dll + name → Bin\\63477BC6
  FUN_100024e0  open master file, verify 16-byte header
  FUN_100025c0  read [u16 flag][0x16 skip][0x14 payload] records from
                +0x40; decode each:
                  w   = rec_u16_LE[i] ^ ((blob[i+1] << 8) | blob[i])
                  out = w // blob[0x16+i]        (unsigned division)
                  entry[i] = out ^ mask[i]
                → the accepted-password table (DAT_100d2380,
                count DAT_100cedf0)
  FUN_1000cc5b  an SGBD is loadable only if one of its password records
                (dir[0] section: u32 count + count×10 bytes) EQUALS a
                table entry.  SECUR1/SECUR2 both carry exactly the three
                decoded entries → they load with the STANDARD EDIABAS
                master passwords; there is no SECUR-specific protection.

  FUN_100027b0  the object-file READ-AND-DECODE wrapper: every byte read
                through it is XORed with 0xF7. That is the whole .PRG
                "encryption": body = file bytes XOR 0xF7 (names, strings
                and pseudocode alike).  Verified by full-text decode.

Output: SECUR_DECODED.md + /tmp/SECUR{1,2}.dec for manual inspection.
"""

import hashlib
import os
import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).parent
EBAS = Path.home() / "Downloads/BMW_Flashing_Binaries/ebas32.dll"
MASTER = (ROOT / "standard_tools" /
          "code$GetEDIABASInstallDir/Bin/63477BC6")
SECUR = {"SECUR1": ROOT / "sgbd/SECUR1.PRG",
         "SECUR2": ROOT / "sgbd/SECUR2.PRG"}


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def load_blob() -> bytes:
    """The obfuscated descriptor blob at ebas32 .rdata 0x1002e12e."""
    import pefile
    pe = pefile.PE(str(EBAS))
    base = pe.OPTIONAL_HEADER.ImageBase
    data = EBAS.read_bytes()
    rva = 0x1002e12e - base
    for s in pe.sections:
        if s.VirtualAddress <= rva < s.VirtualAddress + s.Misc_VirtualSize:
            off = s.PointerToRawData + (rva - s.VirtualAddress)
            return data[off:off + 0x120]
    raise RuntimeError("blob section not found")


def master_filename(blob: bytes) -> str:
    """FUN_10002330: hex-nibble encode blob[0x1c:0x20]."""
    return blob[0x1c:0x20].hex().upper()


def decode_password_table(blob: bytes, master: bytes) -> list:
    """FUN_100025c0: [u16 flag][0x16 skip][0x14 payload] records."""
    mask = blob[0x2a:0x34]
    table = []
    pos = 0x40
    flag = struct.unpack("<H", master[pos:pos + 2])[0]
    pos += 2
    while pos + 0x2a <= len(master):
        pos += 0x16
        payload = master[pos:pos + 0x14]
        pos += 0x14
        if flag != 0:
            out = bytearray(10)
            for i in range(10):
                w = struct.unpack("<H", payload[i * 2:i * 2 + 2])[0]
                w ^= (blob[i + 1] << 8) | blob[i]        # [C] CONCAT11
                d = blob[0x16 + i]
                out[i] = ((w // 250) if d == 0 else (w // d)) & 0xFF
                if out[i] == 0:
                    break
            table.append(bytes(out[i] ^ mask[i] for i in range(10)))
        if pos + 2 > len(master):
            break                                   # _read fails → stop
        flag = struct.unpack("<H", master[pos:pos + 2])[0]
        pos += 2
    return table


def prg_password_records(prg: bytes) -> list:
    """FUN_1000cc5b: dir[0] → u32 count + count×10-byte records."""
    off = struct.unpack("<I", prg[0x78:0x7c])[0]
    (cnt,) = struct.unpack("<I", prg[off:off + 4])
    return [prg[off + 4 + i * 10:off + 4 + (i + 1) * 10]
            for i in range(cnt)]


def xor_f7(data: bytes) -> bytes:
    """FUN_100027b0: the whole .PRG body is stored XOR 0xF7."""
    return bytes(b ^ 0xF7 for b in data)


def main() -> int:
    out = ["# SECUR1/SECUR2 decoded + ebas32 master-password chain",
           "",
           "Generated by secur_decode.py — every step below is "
           "reproduced offline from the binaries in this project set.",
           ""]
    ok = True

    blob = load_blob()
    name = master_filename(blob)
    out += ["## ebas32.dll master-password chain",
            "",
            f"* ebas32.dll SHA-256 `{sha256(EBAS)}`",
            f"* obfuscated descriptor @0x1002e12e → master filename "
            f"**{name}**",
            f"* `{MASTER.name}` SHA-256 `{sha256(MASTER)}` "
            f"({MASTER.stat().st_size} bytes)"]
    ok &= name == "63477BC6"

    table = decode_password_table(blob, MASTER.read_bytes())
    out += [f"* decoded accepted-password table "
            f"({len(table)} entries):"]
    for i, e in enumerate(table):
        out += [f"    `pwd[{i}] = {e.hex()}`"]

    for label, path in SECUR.items():
        prg = path.read_bytes()
        recs = prg_password_records(prg)
        match = all(any(r == t for t in table) for r in recs)
        ok &= match
        out += ["", f"## {label}.PRG (SHA-256 `{sha256(path)}`)", "",
                f"* password records ({len(recs)}): "
                + ", ".join(r.hex() for r in recs),
                f"* **all records match the master table: {match}** "
                f"→ loads with standard EDIABAS passwords"]
        dec = xor_f7(prg)
        Path(f"/tmp/{label}.dec").write_bytes(dec)
        strs = re.findall(rb"[ -~]{6,}", dec)
        out += [f"* XOR-0xF7 decode → {len(strs)} printable runs; "
                f"identity strings:"]
        for s in strs[:6]:
            out += [f"    `{s[:70].decode('latin-1')}`"]
        jobs = sorted(set(m.group().decode() for m in re.finditer(
            rb"JOBNAME:[A-Z0-9_]+", dec)))
        out += ["* jobs defined: " + ", ".join(jobs)]

    out += ["", "## What SECUR1/SECUR2 actually are", "",
            "Both are the ECU-side AUTHENTICATION PROTOCOL SGBDs (BEST/2 "
            "pseudocode, BMW EE-32 B. Schikora / Remes GmbH):",
            "AUTHENTISIERUNG_ZUFALLSZAHL_LESEN (UDS $07 "
            "RequestForAuthentication, result ZUFALLSZAHL = seed), "
            "AUTHENTISIERUNG_START (UDS $08 ReleaseAuthentication — the "
            "COMPUTED KEY arrives as job arguments, documented as "
            "'Byte 21,.... : Schluesseldaten'), FLASH_SIGNATUR_PRUEFEN "
            "(UDS $09 CheckSignature).",
            "",
            "**Runtime keys 1/2 are NOT embedded in SECUR1/SECUR2** — "
            "the key material only flows through them as job arguments. "
            "The carrier remains the winkfpt ATBALGO "
            "'Schluesselworttabelle' def-file (FUN_0046f350), which is "
            "not present in the current data set; the .C0x files in "
            "E60_daten/daten are NFS coding-data containers without "
            "key tables.", "",
            "## Checks", "",
            f"* master filename decode: "
            f"{'PASS' if name == '63477BC6' else 'FAIL'} ({name})",
            f"* SECUR password records match master table: "
            f"{'PASS' if ok else 'FAIL'}", "",
            f"**{'ALL CHECKS PASSED' if ok else 'CHECKS FAILED'}**", ""]
    Path(__file__).with_name("SECUR_DECODED.md").write_text("\n".join(out))
    print("\n".join(out[-8:]))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
