#!/usr/bin/env python3
"""SP-Daten provenance scan: extract the VDLE flash-protocol constants
from the REAL E60 data set the user supplied, with SHA-256 provenance.

What is scanned:
  E60_daten/sgdat/08010408*.ipo, 08020201ULF2HI.ipo — compiled EDIABAS
  SGBD pseudocode that IMPLEMENTS the VDLE device jobs (INIT_VDLE,
  REQUEST_SEGMENTINFO, SEND_SEGMENT, START/STOP_TESTERPRESENT) and the
  ECU-side authentication/flash UDS routines. These are the counterpart
  of everything winkfpt.exe does on the other side of the api32 boundary.
  sgbd/SECUR1.PRG, SECUR2.PRG — encrypted security SGBDs (candidate
  carriers of the runtime keys 1/2 that reach winkfpt via def-files).
  standard_tools/.../Bin — the shipping EDIABAS distribution (IFH
  drivers); md5-compared with the binaries this project reversed.

Output: SPDATEN.md.
"""

import hashlib
import re
import subprocess
import sys
import os
from pathlib import Path

ROOT = Path(__file__).parent
SGDAT = Path(os.environ.get("SPDATEN_SGDAT", ROOT / "E60_daten" / "sgdat"))
SGBD = Path(os.environ.get("SPDATEN_SGBD", ROOT / "sgbd"))
EDIABAS_BIN = Path(os.environ.get("EDIABAS_BIN", ROOT / "standard_tools" / "code$GetEDIABASInstallDir" / "Bin"))
NFS_BIN = Path(os.environ.get("NFS_BIN", ROOT / "standard_tools" / "code$GetNFSInstallDir" / "BIN"))

VDLE_IPOS = [
    "08010408CI62F1.ipo", "08010408CI63F1.ipo",
    "08010408CIA0F1.ipo", "08020201ULF2HI.ipo",
]

EXTRACT = {
    "flash parameters": rb"0x[0-9A-Fa-f]{2};\d+;\d+;\d+;\w+",
    "auth methods": rb"Asymetrisch|Symetrisch|Simple",
    "auth key slots": rb"T_SM[ABC]",
    "VDLE jobs": (rb"INIT_VDLE|EXIT_VDLE|REQUEST_SEGMENTINFO|"
                  rb"SEND_SEGMENT|RESEND_SEGMENT|NR_OF_SEGMENTS|"
                  rb"REQUESTDOWNLOADBUFFER|START_TESTERPRESENT|"
                  rb"STOP_TESTERPRESENT"),
    "UDS flash routines": (rb"NG_AUTHENTISIERUNG_START|NG_FLASH_LOESCHEN|"
                           rb"NG_SIGNATUR_PRUEFEN|"
                           rb"FLASH_SCHREIBEN_XXL|FLASH_SCHREIBEN_ENDE|"
                           rb"FLASH_SCHREIBEN_ADRESSE|"
                           rb"FLASH_BLOCKLAENGE_GESAMT|"
                           rb"FLASH_PROGRAMMIER_STATUS"),
    "timing results": (rb"FLASH_LOESCHZEIT|FLASH_SIGNATURTESTZEIT|"
                       rb"FLASH_RESETZEIT|FLASH_AUTHENTISIERZEIT|"
                       rb"STEUERN_TP_INTERVALL|STEUERN_DLE_TP"),
    "processor": rb"HC12[A-Z0-9]*|PROC[A-Z0-9_]*",
    "max block len": rb"MXBL|64000",
    "auth seed read": (rb"SERIENNUMMER_LESEN|"
                       rb"AUTHENTISIERUNG_ZUFALLSZAHL_LESEN|"
                       rb"ZUFALLSZAHL"),
}


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for blk in iter(lambda: f.read(1 << 16), b""):
            h.update(blk)
    return h.hexdigest()


def strings(p: Path) -> bytes:
    raw = p.read_bytes()
    # printable-ASCII runs >= 4, exactly what `strings` shows
    return b"\n".join(m.group() for m in
                      re.finditer(rb"[ -~]{4,}", raw))


def main() -> int:
    if not SGDAT.is_dir():
        print("Notice: spdaten_scan requires original SP-Daten archives not redistributed with repository:")
        print(f"  SGDAT: Missing ({SGDAT})")
        print("Set SPDATEN_SGDAT environment variable to run in a lab environment with SP-Daten archives.")
        return 0

    out = ["# SP-Daten provenance scan — real E60 data set", "",
           "Generated by spdaten_scan.py. All constants below are read "
           "from the supplied data set; every file is SHA-256-pinned.",
           ""]

    # ---- VDLE SGBDs ---------------------------------------------------
    out += ["## VDLE flash SGBDs (compiled EDIABAS pseudocode, .ipo)", ""]
    for name in VDLE_IPOS:
        p = SGDAT / name
        if not p.exists():
            out += [f"### {name} — MISSING", ""]
            continue
        s = strings(p)
        found = {k: sorted(set(m.decode() for m in re.findall(rx, s)))
                 for k, rx in EXTRACT.items()}
        out += [f"### {name}", "",
                f"SHA-256: `{sha256(p)}`", ""]
        for k, vals in found.items():
            if vals:
                out += [f"- {k}: {', '.join(vals[:14])}"
                        + (" …" if len(vals) > 14 else "")]
        out += [""]
    out += ["Interpretation of the `FLASH_PARAMETER_SETZEN` arguments "
            "(rev 9 cross-section over all 195 sgdat IPOs, refined in "
            "rev 10 by the sgidX.as2 key containers — KEYS_AS2.md):", "",
            "- **field 1 = SG_ADRESSE [C]**: `0x62` in 90 IPOs (the CI62F1 "
            "family — value matches the SGBD name), `0x63` in exactly one "
            "(31AMP60.ipo — the amplifier ECU at 0x63), and `0x00` in 75 "
            "IPOs — the DEFAULT branch right next to "
            "`FLASH_PARAMETER_LESEN → SG_ADRESSE` (both variants sit in "
            "every IPO; the branch picks read-address vs default).",
            "- **field 3 = `18` [C-observed correlation, rev 10]**: every "
            "EGS-mechatronic key record id in sgidC/sgidD ends in `18` "
            "(GKE192 = `2L18`, GKE191 = `MG18`, …) — the key-table "
            "GENERATION of this data set.  `2` and `1` stay [H] "
            "(PABD VM semantics; candidates: slot/count flags).",
            "- **field 5 = auth mode [C]**: `simple` everywhere — one of "
            "exactly the three method names winkfpt's KrApiAuthenticate "
            "switches on (Asymetrisch/Symetrisch/Simple, FUN_004b95a0). "
            "Rev 10: this is the PREFERRED art; the container record "
            "class for the concrete ECU decides what is actually "
            "possible (GKE192 only carries a 16-byte Symmetrisch "
            "record — the length gate FUN_004b89a0 would reject Simple "
            "for it), and the IPO offers the art per the ECU's "
            "AUTHENTISIERUNG response (T_SMA/T_SMB/T_SMC flags).",
            "",
            "The IPO context around the constant (`SG_PHYS_HWNR_LESEN` → "
            "`JOB_ANZAHL 18` → `GetDiagProt/SetDiagProt` → `SetEcuAdr` → "
            "`FLASH_PARAMETER_SETZEN`) shows the call is part of the "
            "session setup sequence, executed before the VDLE download "
            "phase (see WAS_ORCHESTRATION.md).", ""]

    # ---- SECUR1/2 ------------------------------------------------------
    out += ["## SECUR1.PRG / SECUR2.PRG (sgbd/)", ""]
    for name in ("SECUR1.PRG", "SECUR2.PRG"):
        p = SGBD / name
        s = strings(p)
        readable = [x.decode() for x in re.findall(rb"[ -~]{4,}", s)][:2]
        out += [f"- {name}: SHA-256 `{sha256(p)}`, readable strings: "
                f"{readable} — body is ENCRYPTED/encoded EDIABAS "
                f"pseudocode (only the `@EDIABAS OBJECT` header and the "
                f"module name are plaintext)."]
    out += ["",
            "**DECODED in rev 8** (see secur_decode.py → SECUR_DECODED.md): "
            "the .PRG body is a plain XOR-0xF7 encoding applied by the "
            "ebas32 read wrapper FUN_100027b0, and the password gate "
            "uses the standard EDIABAS master file `Bin/63477BC6`. "
            "SECUR1/SECUR2 are the ECU-side authentication protocol SGBDs "
            "(jobs NORMALER_DATENVERKEHR, DIAGNOSE_AUFRECHT, "
            "AUTHENTISIERUNG_*, FLASH_*); runtime keys 1/2 are NOT "
            "embedded — they arrive as job arguments from winkfpt's "
            "ATBALGO def-file, which is still outside the data set.", ""]

    # ---- distribution identity -----------------------------------------
    out += ["## Shipping-distribution identity (md5)", "",
            "| binary | reversed-set md5 | distribution md5 | match |",
            "|---|---|---|---|"]
    ours = Path.home() / "Downloads/BMW_Flashing_Binaries"
    pairs = [("winkfpt.exe", NFS_BIN), ("nfs.exe", NFS_BIN),
             ("KmmSrv.dll", NFS_BIN), ("api32.dll", EDIABAS_BIN),
             ("ebas32.dll", EDIABAS_BIN), ("Best32.dll", EDIABAS_BIN)]
    for name, dist_dir in pairs:
        o, d = ours / name, dist_dir / name
        mo = subprocess.run(["md5", "-q", str(o)],
                            capture_output=True, text=True).stdout.strip()
        md = subprocess.run(["md5", "-q", str(d)],
                            capture_output=True, text=True).stdout.strip()
        out += [f"| {name} | {mo} | {md} | {'YES' if mo == md else 'NO'} |"]
    out += ["",
            "The binaries this project reverse-engineered are "
            "byte-identical to the shipped EDIABAS/INPA/NCS/NFS "
            "distribution.", ""]

    # ---- EDIABAS.INI (deployment config) --------------------------------
    out += ["## EDIABAS.INI — deployment configuration", ""]
    ini_dist = EDIABAS_BIN / "EDIABAS.INI"
    inis = [("distribution Bin/EDIABAS.INI", ini_dist)]
    for nm in ("EDIABAS 2.INI", "EDIABAS 3.INI", "EDIABAS 4.INI",
               "Ediabas.ini"):
        p = ROOT / nm
        if p.exists():
            inis.append((nm, p))
    for label, p in inis:
        txt = p.read_bytes().decode("cp1252", "replace")
        iface = re.search(rb"Interface\s*=\s*(\S+)", txt.encode("cp1252",
                                                                "replace"))
        host = re.search(rb"RemoteHost\s*=\s*(\S+)", txt.encode("cp1252",
                                                                "replace"))
        port = re.search(rb"Port\s*=\s*(\S+)", txt.encode("cp1252",
                                                          "replace"))
        sim = re.search(rb"Simulation\s*=\s*(\S+)", txt.encode("cp1252",
                                                               "replace"))
        out += [f"- `{label}` — SHA-256 `{sha256(p)[:16]}…`, "
                f"Interface={iface.group(1).decode() if iface else '-'}"
                f"{', TCP ' + host.group(1).decode() + ':' + port.group(1).decode() if host and port else ''}"
                f"{', Simulation=' + sim.group(1).decode() if sim else ''}"]
    out += ["",
            "Two real deployment variants: **STD:FUNK** → TCP diagnostic "
            "head `LMUC203404:3000` (EDIABAS 2/4 == distribution, "
            "FUNK32.dll), and **STD:OBD** → TCP `192.168.68.1:6801` "
            "(EDIABAS 3 — an Ethernet OBD head on the local bench "
            "network). XEthernet tester addresses F4/F5 in the "
            "distribution INI match the MOST tester addresses the CI62 "
            "SGBD programs (STEUERN_MOST_TESTER_ADRESSE 0xF5/0xFA). The "
            "IFH layer itself remains outside the reconstruction, but "
            "the deployment side is now documented.", ""]

    # ---- IFH drivers now present ----------------------------------------
    drivers = sorted(d.name for d in EDIABAS_BIN.glob("*.dll")
                     if re.match(r"(X|rdr|VMCI|FUNK)", d.name, re.I))
    out += ["## IFH transport drivers (previously outside the set)", ""]
    out += [f"`{d}`" for d in drivers[:20]] + ["",
            "The IFH layer is still not reverse-engineered, but the "
            "driver binaries are now available in-set for future work.",
            ""]

    Path(__file__).with_name("SPDATEN.md").write_text("\n".join(out))
    print(f"SPDATEN.md written ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
